spring:
  application:
    name: board-game-rent-application
  profiles:
    active: info
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      username: evgen
      password: evgen