version: "3.5"

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=boardgamerent
      - MYSQL_USER=evgen
      - MYSQL_PASSWORD=evgen
      - MYSQL_ROOT_PASSWORD=evgen
  config:
    image: config
    ports:
      - 8888:8888