version: "3.5"

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
  config:
    image: config-server
    ports:
      - 8888:8888
    environment:
      - PROPERTY_PATH=$PROPERTY_PATH
      - USER_NAME=$USER_NAME
      - PASSWORD=$PASSWORD
      - SECRET=$SECRET

